image: "gitpod/workspace-node:latest"

tasks:
  - init: |
      pip install jupyter
      pnpm install
    command: |
      jupyter notebook --ip=0.0.0.0 --no-browser --allow-root &
      pnpm start:localfhenix

vscode:
  extensions:
    - "esbenp.prettier-vscode"
    - "NomicFoundation.hardhat-solidity"
    - "ritwickdey.LiveServer"
